### ISSUE TITLE
I find a bug!

### ISSUE THREAD

**Issue by 836438020** [laravel-admin-extensions/backup#11]
When I click the Backup button,
I find a ajax request to backend,so I wait a moment,
this response a json as 
{"status":false,"message":"Connection to smtp.mailtrap.io:2525 Timed Out"}

**Comment by fangke2688** [comment]
把notifications数组中的mail删除即可
![image](https://user-images.githubusercontent.com/26641510/63635431-1d915000-c695-11e9-923e-4a2a3f4e0c89.png)
