### ISSUE TITLE
备份失败

### ISSUE THREAD

**Issue by lxin87** [laravel-admin-extensions/backup#7]
1.程序装在本机
2.mysql装在内网的其它机器上
出现两个问题
1.大致的提示是说swiftmailer这个包发送邮件失败，后来猜想是备份有邮件提示，但是没有找到配置邮件的地方，后来看到这个包是依赖spatie/laravel-backup,它下面有配置文件:
`php artisan vendor:publish`
把backup.php文件发布到config目录下，改下里面的 mail to 项目就好了
2.上面问题解决之后又出现另外一个问题
`Backup failed because The dump process failed with exitcode 127 : Command not found : sh: mysqldump: command not found`

我尝试着把mysqldump把软链到/usr/local/bin  然后再执行，还是报同样的错误。
我的是Mac电脑，不知道该如何解决了

**Comment by RealZark** [comment]
```
//config/database.php
'connections' => [
	'mysql' => [
		'driver'    => 'mysql'
		...,
		'dump' => [
		   'dump_binary_path' => '/path/to/the/binary', // only the path, so without `mysqldump` or `pg_dump`
		   'use_single_transaction',
		   'timeout' => 60 * 5, // 5 minute timeout
		   'exclude_tables' => ['table1', 'table2'],
		   'add_extra_option' => '--optionname=optionvalue', 
		]  
	],
```
在 `database.php` 配置文件内加上这个配置，配置项的值自己看着填。详情链接看[这里](https://docs.spatie.be/laravel-backup/v4/installation-and-setup)。
