### ISSUE TITLE
Pjax导致点击下载备份超链接时页面卡死

### ISSUE THREAD

**Issue by zanemmm** [laravel-admin-extensions/backup#8]
@z-song 在直接点击下载备份超链接的时候,因为后台页面用了pjax所以不是正常的下载,前端直接将收到的压缩包给渲染了并且这个过程浏览器会很卡.最后变成了乱码.

如图所示:

![_ _20180202230852](https://user-images.githubusercontent.com/23761319/35739886-1149b012-086e-11e8-91e3-91ba09256c54.png)

我的解决方案是将下载的a标签加上 `target="_blank"`, 在新的页面打开下载地址.

即修改 `resources/views/index.blade.php` 的第 `122` 行.

如下:

```html
 <a target="_blank" href="{{ route('backup-download', ['disk' => $backup[1], 'file' => $backup[0].'/'.$file]) }}"><i class="fa fa-download"></i></a>

```

emmm...希望作者尽快修复,因为我不想直接修改 composer 里的代码.

PS: 能提个建议么,我发现 laravel-admin-extensions 里的包都不支持自定义路由,如果对视图或者路由不满意貌似最快的方法是直接改包里的代码,但是这样好像并不优雅.emmm...所以真心希望作者提供自定义路由的功能.

最后还是感谢提供如此好用的laravel后台包 :+1: :smiley:

**Comment by z-song** [comment]
#6
